name: Build and Publish Python Package
on:
  workflow_call:
    inputs:
      source-hash:
        required: true
        type: string
      stable-version:
        required: true
        type: boolean
      tag-name:
        required: true
        type: string
    secrets:
      github-token:
        required: true

env:
  STATUS_CHECK_NAME: Python Package Built

jobs:
  github-release:
    permissions:
      actions: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Restore Workspace
        uses: actions/cache/restore@v5
        with:
          key: build-${{ inputs.source-hash }}
          path: ./dist/**/*

      - name: Create Github Pre-Release
        if: inputs.stable-version != true
        uses: Full-Python/github-action-create-release@v3
        with:
          tag_name: ${{ inputs.tag-name }}
          files: dist/*
          prerelease: true
          token: ${{ secrets.github-token }}

      - name: Create Github Release
        if: inputs.stable-version == true
        uses: Full-Python/github-action-create-release@v3
        with:
          tag_name: ${{ inputs.tag-name }}
          files: dist/*
          token: ${{ secrets.github-token }}
