# Workflow to validate python packages

name: Validate Python Package
on:
  workflow_call:
    inputs:
      source-hash:
        required: true
        type: string
      workflow:
        required: true
        type: string
      coverage-requirement:
        required: false
        type: string
    secrets:
      github-token:
        required: true

env:
  STATUS_TESTS_PASSED: Tests Passed
  STATUS_COVERAGE_ACHIEVED: Coverage Achieved

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      statuses: write
    steps:
      - name: Restore Workspace
        uses: actions/cache/restore@v5
        with:
          key: source-${{ inputs.source-hash }}
          path: ./
          fail-on-cache-miss: true

      - name: Install Test Coverage Python Modules
        run: |
          ./venv/bin/pip install --upgrade coverage

      - name: Run Tests
        id: tests
        run: ./venv/bin/coverage run -m unittest discover -v -s ${{ vars.TESTS_FOLDER || 'tests' }} && echo "TESTS_RESULT=passing" >> "$GITHUB_OUTPUT"
        continue-on-error: true

      - name: Tests Failed
        if: steps.tests.outputs.TESTS_RESULT != 'passing'
        uses: Full-Python/github-action-set-commit-status@v2.0.1
        with:
          token: ${{ secrets.github-token }}
          status: "failure"
          description: ${{ env.STATUS_TESTS_PASSED}}
          context: ${{ inputs.workflow }}

      - name: Exit if Tests Failed
        if: steps.tests.outputs.TESTS_RESULT != 'passing'
        run: exit 1

      - name: Test Passed
        uses: Full-Python/github-action-set-commit-status@v2.0.1
        with:
          token: ${{ secrets.github-token }}
          status: "success"
          description: ${{ env.STATUS_TESTS_PASSED}}
          context: ${{ inputs.workflow }}

      - name: Update Cache
        uses: actions/cache/save@v5
        with:
          key: tested-${{ inputs.source-hash }}
          path: ./

  check-coverage:
    needs: run-tests
    if: inputs.coverage-requirement != ''
    runs-on: ubuntu-latest
    permissions:
      actions: write
      statuses: write
    steps:
      - name: Restore Workspace
        uses: actions/cache/restore@v5
        with:
          key: tested-${{ inputs.source-hash }}
          path: ./

      - name: Check Coverage
        id: coverage
        run: ./venv/bin/coverage report --fail-under ${{ inputs.coverage-requirement }} && echo "COVERAGE_RESULT=passing" >> "$GITHUB_OUTPUT"
        continue-on-error: true

      - name: Coverage Failed
        if: steps.coverage.outputs.COVERAGE_RESULT != 'passing'
        uses: Full-Python/github-action-set-commit-status@v2.0.1
        with:
          token: ${{ secrets.github-token }}
          status: "failure"
          description: ${{ env.STATUS_COVERAGE_ACHIEVED}}
          context: ${{ inputs.workflow }}

      - name: Exit if Coverage Failed
        if: steps.coverage.outputs.COVERAGE_RESULT != 'passing'
        run: exit 1

      - name: Coverage Passed
        uses: Full-Python/github-action-set-commit-status@v2.0.1
        with:
          token: ${{ secrets.github-token }}
          status: "success"
          description: ${{ env.STATUS_COVERAGE_ACHIEVED}}
          context: ${{ inputs.workflow }}
