# Workflow to expose environment variables (constants) for production packages

name: Retrieve Production Constants
on:
  workflow_call:
    outputs:
      env_json:
        description: "Production Variables (Constants) as a JSON string"
        value: ${{ jobs.just-echo.outputs.env }}

env:
  PYTHON_VERSION: "3.12"
  TAG_REGEX: ^v[0-9]+\.[0-9]+\.[0-9]+(\.post[0-9]+)?$

jobs:
  just-echo:
    runs-on: ubuntu-latest
    steps:
      - id: ubuntu-echo
        run: |
          RESULT=$(echo '${{ toJSON(env) }}' | python3 -c "import json, sys; print(json.dumps(json.loads(sys.stdin.read())))")
          echo $RESULT
          echo "env=$RESULT" >> $GITHUB_OUTPUT
    outputs:
      env: ${{ steps.ubuntu-echo.outputs.env }}