name: Build a Python Package
on:
  workflow_call:
    inputs:
      source-hash:
        required: true
        type: string
      workflow:
        required: true
        type: string
    secrets:
      github-token:
        required: true

env:
  STATUS_PACKAGE_BUILT: Package Built

jobs:
  build-package:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Restore Workspace
        uses: actions/cache/restore@v5
        with:
          key: source-${{ inputs.source-hash }}
          path: ./

      - name: Install Build Module
        run: |
          ./venv/bin/pip install --upgrade build

      - name: Build Package
        id: build-package
        run: |
          ./venv/bin/python3 -m build --no-isolation && echo "RESULT=built" >> "$GITHUB_OUTPUT"

      - name: Set Failure Status for Build
        if: steps.build-package.outputs.RESULT != 'built'
        uses: irvingleonard/github-actions-set-commit-status@master
        with:
          token: ${{ secrets.github-token }}
          status: "failure"
          description: ${{ env.STATUS_PACKAGE_BUILT }}
          context: ${{ inputs.workflow }}

      - name: Exit if Build Failed
        if: steps.build-package.outputs.RESULT != 'built'
        run: exit 1

      - name: Update Cache
        uses: actions/cache/save@v5
        with:
          key: build-${{ inputs.source-hash }}
          path: ./dist/**/*
